<?php


namespace tests\unit;

use PHPUnit\Framework\TestCase;
use src\App\Database;
use src\TableGateway\Person;

class TestDatabase extends TestCase
{
    private $dbCnx;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $db = new Database();
        $this->dbCnx = $db->getConnection();
    }

    public function testDatabaseConnection()
    {

        $person = new Person($this->dbCnx);
        $result = $person->findAll();
        $this->assertEquals([], $result);
    }
}